name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true
    
    - name: Build the Docker image
      run: |
        ./build_target.sh catalogue ${{ secrets.DOCKERHUB_USER }} push
        ./build_target.sh featurestore ${{ secrets.DOCKERHUB_USER }} push
        ./build_target.sh crawlers ${{ secrets.DOCKERHUB_USER }} push
