name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true
    
    - name: Build the Docker image
      run: |
        go get -tags=kerberos github.com/beltran/gosasl
        ./build_target.sh -t all -o ${{ secrets.DOCKERHUB_USER }} --static --push
        ./build_target.sh -t catalogue -o ${{ secrets.DOCKERHUB_USER }} --static --push
        ./build_target.sh -t featurestore -o ${{ secrets.DOCKERHUB_USER }} --static --push
        ./build_target.sh -t crawlers -o ${{ secrets.DOCKERHUB_USER }} --static --push
        ./build_target.sh -t all -o ${{ secrets.DOCKERHUB_USER }} --push
        ./build_target.sh -t catalogue -o ${{ secrets.DOCKERHUB_USER }} --push
        ./build_target.sh -t featurestore -o ${{ secrets.DOCKERHUB_USER }} --push
        ./build_target.sh -t crawlers -o ${{ secrets.DOCKERHUB_USER }} --push