name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install krb5
      run: sudo apt-get install libkrb5-dev

    - name: Build
      run: |
        GO111MODULE=on
        CGO_ENABLED=0
        GOOS=linux
        GOARCH=amd64
        go build -tags=kerberos -o mastro .

    #- name: Test
    #  run: go test -v ./...
